blank_issues_enabled: true
contact_links:
  - name: Support Request
    url: https://github.com/retailmediatools/rmt-sdk-ts/discussions
    about: Please use GitHub Discussions if you have questions about the retailmediatools SDK.
  - name: Report a Security Issue
    url: https://github.com/retailmediatools/rmt-sdk-ts/blob/main/CONTRIBUTING.md#reporting-a-security-vulnerability
    about: Please follow the process for reporting security issues.
