name: Push to main
on:
  push:
    branches: [main]

jobs:
  build-workflow:
    name: Build and test
    uses: ./.github/workflows/reusable-build-workflow.yaml
    with:
      push: true
    secrets: inherit
