---
name: PR Labels

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  # PR labels based on paths changed
  folder-labels:
    runs-on: ubuntu-latest
    name: Label the PRs based on paths changed
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4.0.3
        with:
          repo-token: ${{ github.token }}
          sync-labels: true
