name: Renovate
on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_5_*_*_* "At 05:00"
    - cron: '0 5 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v37.0.0
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RMT_BOT_PAT }}
