name: Reusable build workflow

on:
  workflow_call:

jobs:
  ci:
    name: Build, test and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      #########################
      # Build and test
      #########################
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - run: git fetch --no-tags --prune --depth=5 origin main
      - run: yarn install --immutable

      # lint
      - name: Lint
        run: |
          yarn exec nx affected:lint --base=origin/main --head=HEAD

      # build
      - name: Build
        run: |
          yarn exec nx run-many --target=build --all=true

      # test
      - name: Test
        run: |
          yarn exec nx affected:test --base=origin/main --head=HEAD
